name: Sync
on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: LegoManiac04/file-sync
          event-type: file_sync
