name: Sync
on:
  push

obs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Sync
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" --request POST --data '{"event_type": "file_sync"}' https://api.github.com/repos/LegoManiac04/file-sync/dispatches
