name: File Sync
on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: webhook
        run: |
          curl -X POST https://api.github.com/repos/LegoManiac04/file-sync/dispatches \
          -H 'Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token $TOKEN' \
          --data '{"event_type": event_type"}'
